### ISSUE TITLE
API kullanımı hakkında?

### ISSUE THREAD

**Issue by unicornlox** [codeyapikredi/api#1]
Yapıkredi'nin apisini kullanıp para transfer işlemi yapmayı planlamaktayım. Web api yapmam mümkün mü?Ayrıntılandırmam gerekirse tumblr veya blogger da kullanılmak üzere rest api üzerinden işlemleri yaptırabilir miyim? Güvenlik açığı oluşturmadan bu mümkün mü? Bir nevi Yapıkredi apisini, Paypal api yerine kullanmak istiyorum. Api kullanmanın bir ücreti var mı ve hiçbir kesinti olmadan para gönderilebiliyor mu? Yapmayı planladığım tema tasarımını kendim için değil genel kullanım için yapacağımdan; test için consumer key, token veya auth id almadan uygulamayı test edebileceğim bir yapı var mı?Kısacası üye olmak istemiyorum çünkü üye olursam para alacaklarmış gibi bir korku doğuyor içime, bankalardan hep korkarım :) Bir de bu apileri kullanabilmek için Yapıkredi müşterisi olmak zorunlu mudur? Sorularımı burada sormamın yersiz olduğunu biliyorum ama bu soruların cevabını çağrı merkezinde alacağımı sanmadığımdan burada sordum.
ilgileriniz için şimdiden çok teşekkür ederim.

**Comment by ramazansancar** [comment]
@unicornlox Buradan tüm detaylara ulaşabilirsin

https://apiportal.yapikredi.com.tr/api-catalog

**Comment by unicornlox** [comment]
@ramazansancar teşekkürler:)
